Vagrant.configure("2") do |config|
    
    #Definir le nom de la machine dans vagrant. Replace default
    config.vm.define "formation-prometheus"
    
    #Definir le provider 
    config.vm.provider "virtualbox" do |v|
        #Definir le nom de la VM dans le provider en remplacement de celui par defaut
        v.name = "formation-prometheus"
    end

    #Definir le hostname de la VM
    config.vm.hostname = "formation-prometheus"
    
    config.vm.box = "bento/ubuntu-24.04"
    
    #Installer Docker et télécharger l'image alpine 
    config.vm.provision "docker"

end
