$script = <<-SCRIPT
apt -y update; apt -y install git;
cd /opt; git clone https://github.com/Dynatrace/easytrade.git
cd easytrade; docker compose up -d
SCRIPT

Vagrant.configure("2") do |config|

    #Transfert de port machine -> vm
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "forwarded_port", guest: 9090, host: 9090
    config.vm.network "forwarded_port", guest: 9091, host: 9091
    config.vm.network "forwarded_port", guest: 9100, host: 9100
    config.vm.network "forwarded_port", guest: 3000, host: 3000
    
    #Definir le nom de la machine dans vagrant. Replace default
    config.vm.define "formation-prometheus"
    
    #Definir le provider 
    config.vm.provider "virtualbox" do |v|
        #Definir le nom de la VM dans le provider en remplacement de celui par defaut
        v.name = "formation-prometheus"
    end

    #Definir le hostname de la VM
    config.vm.hostname = "formation-prometheus"
    
    config.vm.box = "bento/ubuntu-24.04"
    
    #Installer Docker et télécharger l'image alpine 
    config.vm.provision "docker" do |d|
        d.pull_images "prom/prometheus"
    end

    #Installer Dynatrace Easytrade 
    #config.vm.provision "shell", inline: $script

end
